.TH CALIBRATE_6022 1 "April 2026" "hantek6022api 2.10.9" "User Commands"
.SH NAME
calibrate_6022 \- calibrate offset and gain of Hantek 6022BE/BL oscilloscope
.SH SYNOPSIS
.B calibrate_6022
[\fB\-c\fR] [\fB\-e\fR] [\fB\-g\fR]
.SH DESCRIPTION
Program to calibrate offset and gain of Hantek 6022BE/BL oscilloscope.
Measures offset at low and high speed for gain steps x10, x5, x2, x1,
and optionally measures gain for these steps.
.SH OPTIONS
.TP
\fB\-c\fR, \fB\-\-create_config\fR
Create config file for OpenHantek.
.TP
\fB\-e\fR, \fB\-\-eeprom\fR
Store calibration values in eeprom.
.TP
\fB\-g\fR, \fB\-\-measure_gain\fR
Interactively measure gain (as well as offset).
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help message and exit.
.SH SEE ALSO
.BR capture_6022 (1),
.BR get_serial_number_6022 (1),
.BR upload_firmware_6022 (1)
