#!/usr/bin/env python3
"""
Set the calibration output frequency of a Hantek 6022BE/BL oscilloscope.

The calibration pulse (GND/probe connector pin) is generated by the firmware,
which codes the frequency into a single byte sent with vendor request 0xe6
(see Firmware/DSO6022BE/scope6022.inc, set_calibration_pulse()):

    byte 103        ->      32 Hz
    byte 104..199   ->  40...990 Hz, step 10 Hz
    byte 201..255   -> 100...5500 Hz, step 100 Hz
    byte 1..100     ->   1...100 kHz, step 1 kHz

The firmware does not generate the coded frequency itself: it loads Timer2 with
the auto reload value 2000000 // coded (scope6022.inc:297) and toggles the pin
on every overflow, so the actual output of coded frequency c is
2 MHz / (2000000 // c) -- only coded frequencies that divide the 2 MHz
reference are produced exactly (32, 100, 500, 1000, 4000, 8000, 20000, 40000,
80000, 100000 Hz...), the others land on the next higher divisor, e.g. every
coded value 77000...80000 Hz yields 80000 Hz.

A requested value between two actual outputs is rounded to the nearest one and
a warning is printed to stderr; --min sets the smallest actual output >= FREQ
(78000 -> 80000 Hz), --max the largest one <= FREQ (78000 -> 76923 Hz). With
--exact such a value is rejected instead.

After setting the frequency the program keeps its USB connection to the scope
open (-t TIME seconds, or until ^C) so the port stays active and the output
keeps running.

usage: frequency_6022 [-h] [-e] [--min | --max] [-t TIME] FREQ
"""

import argparse
import sys
import time

from fractions import Fraction

from PyHT6022.LibUsbScope import Oscilloscope

# the firmware rejects everything outside this range (set_calibration_pulse())
MIN_FREQUENCY = 32
MAX_FREQUENCY = 100000

# the firmware toggles the calibration pin once per Timer2 overflow; Timer2 runs
# at 2 MHz in the calibration use case, so the output is quantized to the
# divisors of this reference (actual = TIMER2_REFERENCE / (TIMER2_REFERENCE // coded))
TIMER2_REFERENCE = 2000000            # Hz


def representable_frequencies():
    """
    All *coded* frequencies in Hz -- the value put into the frequency byte.

    The actual output is quantized to the divisors of the 2 MHz reference, see
    actual_output_frequency() and resolve_frequency().
    :return: sorted list of coded frequencies, see the coding table above.
    """
    return sorted({32,
                   *range(40, 1000, 10),            # 40...990 Hz, 10 Hz steps
                   *range(100, 5600, 100),          # 100...5500 Hz, 100 Hz steps
                   *range(1000, 100001, 1000)})     # 1...100 kHz, 1 kHz steps


def format_frequency(frequency):
    """Render a frequency (int or Fraction) for messages, 2 decimals if not exact."""
    if not isinstance(frequency, Fraction):
        frequency = Fraction(frequency)
    if frequency.denominator == 1:
        return f'{frequency.numerator} Hz'
    return f'{frequency.numerator / frequency.denominator:.2f} Hz'


def actual_output_frequency(coded_frequency):
    """
    Actual output frequency for a coded frequency (int or Fraction), as Fraction.

    The firmware loads Timer2 with the auto reload value 2000000 // coded
    (scope6022.inc:297) and toggles the calibration pin on every overflow, so
    the output is quantized to the divisors of the 2 MHz reference and is only
    exact when the coded frequency divides 2 MHz.
    """
    return Fraction(TIMER2_REFERENCE, TIMER2_REFERENCE // coded_frequency)


def resolve_frequency(frequency, exact=False, rounding='nearest'):
    """
    Map a requested frequency onto the actual output of the frequency counter.

    The frequency byte codes values up to 100 kHz (see the module docstring),
    but the firmware only produces the divisors of its 2 MHz reference exactly;
    every coded value 77000...80000 Hz e.g. yields 80000 Hz.  The chosen coded
    value is the one whose actual output is nearest to, or the smallest above
    / the largest below, the request.

    :param frequency: requested frequency in Hz.
    :param exact: reject frequencies that have no exact actual output.
    :param rounding: 'nearest' (default, ties round up), 'above' (smallest
                     actual output >= frequency) or 'below' (largest actual
                     output <= frequency).
    :return: (coded frequency to send, actual output as Fraction, warning or None)
    :raise ValueError: if exact is True and no actual output equals frequency.
    """
    if rounding not in ('nearest', 'above', 'below'):
        raise ValueError(f'invalid rounding mode {rounding!r}')

    # (actual output, smallest coded value producing it), ascending; the actual
    # output rises because the reload value 2000000 // coded shrinks
    targets = []
    for coded in representable_frequencies():
        actual = actual_output_frequency(coded)
        if not targets or targets[-1][0] != actual:
            targets.append((actual, coded))

    if any(actual == frequency for actual, _ in targets):
        coded = next(c for actual, c in targets if actual == frequency)
        return coded, Fraction(frequency), None

    if exact:
        lower = max((actual for actual, _ in targets if actual < frequency),
                    default=None)
        upper = min((actual for actual, _ in targets if actual > frequency),
                    default=None)
        neighbour = ' or '.join(format_frequency(value)
                                for value in (lower, upper) if value is not None)
        raise ValueError(f'{frequency} Hz cannot be produced exactly, '
                         f'nearest actual outputs: {neighbour}')

    if rounding == 'above':
        target = next(t for t in targets if t[0] >= frequency)
    elif rounding == 'below':
        target = next(t for t in reversed(targets) if t[0] <= frequency)
    else:
        target = min(targets, key=lambda t: (abs(t[0] - frequency), -t[0]))
    actual, coded = target
    return (coded, actual,
            f'{frequency} Hz is not representable, '
            f'using {format_frequency(actual)}')


def build_arg_parser():
    """Construct the argument parser for the frequency_6022 command."""
    parser = argparse.ArgumentParser(
        description='Set the calibration output frequency of Hantek6022'
    )
    parser.add_argument(
        'frequency',
        type=int,
        metavar='FREQ',
        help=f'calibration frequency in Hz ({MIN_FREQUENCY} ... {MAX_FREQUENCY})'
    )
    parser.add_argument(
        '-e', '--exact',
        action='store_true',
        help='fail if FREQ cannot be produced exactly instead of rounding it'
    )
    rounding = parser.add_mutually_exclusive_group()
    rounding.add_argument(
        '--min',
        action='store_true',
        help='set the smallest actual output frequency >= FREQ (78000 -> 80000 Hz)'
    )
    rounding.add_argument(
        '--max',
        action='store_true',
        help='set the largest actual output frequency <= FREQ (78000 -> 76923 Hz)'
    )
    parser.add_argument(
        '-t', '--time',
        type=float,
        metavar='TIME',
        help='hold the USB connection open for TIME seconds so the calibration '
             'output keeps running (default: until interrupted)'
    )
    return parser


def main(args=None):
    """
    Command entry point.
    :param args: Command line arguments, default: sys.argv.
    :return: Exit status.
    """
    parser = build_arg_parser()
    options = parser.parse_args(args)

    if not MIN_FREQUENCY <= options.frequency <= MAX_FREQUENCY:
        parser.error(f'frequency must be between {MIN_FREQUENCY} '
                     f'and {MAX_FREQUENCY} Hz')

    if options.time is not None and options.time <= 0:
        parser.error('--time must be positive')

    try:
        coded_frequency, actual_frequency, warning = resolve_frequency(
            options.frequency,
            options.exact,
            'above' if options.min else 'below' if options.max else 'nearest')
    except ValueError as error:
        sys.stderr.write(f'error: {error}\n')
        return 1
    if warning:
        sys.stderr.write(f'warning: {warning}\n')

    scope = Oscilloscope()
    if not scope.open_handle():
        sys.stderr.write('scope open error - no device?\n')
        return 1

    try:
        # upload the firmware into the RAM of the device if not present
        if not scope.is_device_firmware_present:
            sys.stderr.write('Upload firmware...\n')
            scope.flash_firmware()

        if not scope.set_calibration_frequency(coded_frequency):
            sys.stderr.write(f'error: cannot set {coded_frequency} Hz\n')
            return 1

        print(f'calibration frequency: {format_frequency(actual_frequency)}')

        # keep the USB connection open so the port does not autosuspend and
        # the (software generated) calibration output keeps running
        if options.time:
            time.sleep(options.time)
        else:
            sys.stderr.write('keeping the calibration output running, ^C to stop\n')
            while True:
                time.sleep(60)
    except KeyboardInterrupt:
        sys.stderr.write('\nstopped\n')
        return 0
    finally:
        scope.close_handle()

    return 0


if __name__ == "__main__":
    sys.exit(main())
