#!/usr/bin/env python3
"""
Set the calibration output frequency of a Hantek 6022BE/BL oscilloscope.

The calibration pulse (GND/probe connector pin) is generated by the firmware,
which codes the frequency into a single byte sent with vendor request 0xe6
(see Firmware/DSO6022BE/scope6022.inc, set_calibration_pulse()):

    byte 103        ->      32 Hz
    byte 104..199   ->  40...990 Hz, step 10 Hz
    byte 201..255   -> 100...5500 Hz, step 100 Hz
    byte 1..100     ->   1...100 kHz, step 1 kHz

A requested value between two steps is rounded to the nearest representable
frequency and a warning is printed to stderr; --min sets the smallest
representable frequency >= FREQ (433 -> 440 Hz), --max the largest one <= FREQ
(433 -> 430 Hz). With --exact such a value is rejected instead.

After setting the frequency the program keeps its USB connection to the scope
open (-t TIME seconds, or until ^C) so the port stays active and the output
keeps running.

usage: frequency_6022 [-h] [-e] [--min | --max] [-t TIME] FREQ
"""

import argparse
import sys
import time

from PyHT6022.LibUsbScope import Oscilloscope

# the firmware rejects everything outside this range (set_calibration_pulse())
MIN_FREQUENCY = 32
MAX_FREQUENCY = 100000


def representable_frequencies():
    """
    All frequencies in Hz that the firmware can generate.
    :return: sorted list of frequencies, see the coding table above.
    """
    return sorted({32,
                   *range(40, 1000, 10),            # 40...990 Hz, 10 Hz steps
                   *range(100, 5600, 100),          # 100...5500 Hz, 100 Hz steps
                   *range(1000, 100001, 1000)})     # 1...100 kHz, 1 kHz steps


def nearest_frequency(frequency):
    """Return the representable frequency closest to frequency (ties round up)."""
    return min(representable_frequencies(),
               key=lambda value: (abs(value - frequency), -value))


def resolve_frequency(frequency, exact=False, rounding='nearest'):
    """
    Map a requested frequency onto the representable ones.
    :param frequency: requested frequency in Hz.
    :param exact: reject frequencies that cannot be set exactly.
    :param rounding: 'nearest' (default, ties round up), 'above' (set the
                     smallest representable frequency >= frequency) or 'below'
                     (set the largest representable frequency <= frequency).
    :return: (frequency to set, warning text or None)
    :raise ValueError: if exact is True and the frequency is not representable.
    """
    if rounding not in ('nearest', 'above', 'below'):
        raise ValueError(f'invalid rounding mode {rounding!r}')
    values = representable_frequencies()
    if frequency in values:
        return frequency, None
    if exact:
        lower = max(value for value in values if value <= frequency)
        upper = min(value for value in values if value >= frequency)
        raise ValueError(f'{frequency} Hz cannot be set exactly, '
                         f'nearest: {lower} Hz or {upper} Hz')
    if rounding == 'above':
        target = min(value for value in values if value >= frequency)
    elif rounding == 'below':
        target = max(value for value in values if value <= frequency)
    else:
        target = nearest_frequency(frequency)
    return target, f'{frequency} Hz is not representable, using {target} Hz'


def build_arg_parser():
    """Construct the argument parser for the frequency_6022 command."""
    parser = argparse.ArgumentParser(
        description='Set the calibration output frequency of Hantek6022'
    )
    parser.add_argument(
        'frequency',
        type=int,
        metavar='FREQ',
        help=f'calibration frequency in Hz ({MIN_FREQUENCY} ... {MAX_FREQUENCY})'
    )
    parser.add_argument(
        '-e', '--exact',
        action='store_true',
        help='fail if FREQ is not representable instead of rounding it'
    )
    rounding = parser.add_mutually_exclusive_group()
    rounding.add_argument(
        '--min',
        action='store_true',
        help='set the smallest representable frequency >= FREQ (433 -> 440 Hz)'
    )
    rounding.add_argument(
        '--max',
        action='store_true',
        help='set the largest representable frequency <= FREQ (433 -> 430 Hz)'
    )
    parser.add_argument(
        '-t', '--time',
        type=float,
        metavar='TIME',
        help='hold the USB connection open for TIME seconds so the calibration '
             'output keeps running (default: until interrupted)'
    )
    return parser


def main(args=None):
    """
    Command entry point.
    :param args: Command line arguments, default: sys.argv.
    :return: Exit status.
    """
    parser = build_arg_parser()
    options = parser.parse_args(args)

    if not MIN_FREQUENCY <= options.frequency <= MAX_FREQUENCY:
        parser.error(f'frequency must be between {MIN_FREQUENCY} '
                     f'and {MAX_FREQUENCY} Hz')

    if options.time is not None and options.time <= 0:
        parser.error('--time must be positive')

    try:
        frequency, warning = resolve_frequency(
            options.frequency,
            options.exact,
            'above' if options.min else 'below' if options.max else 'nearest')
    except ValueError as error:
        sys.stderr.write(f'error: {error}\n')
        return 1
    if warning:
        sys.stderr.write(f'warning: {warning}\n')

    scope = Oscilloscope()
    if not scope.open_handle():
        sys.stderr.write('scope open error - no device?\n')
        return 1

    try:
        # upload the firmware into the RAM of the device if not present
        if not scope.is_device_firmware_present:
            sys.stderr.write('Upload firmware...\n')
            scope.flash_firmware()

        if not scope.set_calibration_frequency(frequency):
            sys.stderr.write(f'error: cannot set {frequency} Hz\n')
            return 1

        print(f'calibration frequency: {frequency} Hz')

        # keep the USB connection open so the port does not autosuspend and
        # the (software generated) calibration output keeps running
        if options.time:
            time.sleep(options.time)
        else:
            sys.stderr.write('keeping the calibration output running, ^C to stop\n')
            while True:
                time.sleep(60)
    except KeyboardInterrupt:
        sys.stderr.write('\nstopped\n')
        return 0
    finally:
        scope.close_handle()

    return 0


if __name__ == "__main__":
    sys.exit(main())
